# vim: fdm=marker fdl=0
# from velocity data only get x-t data
#	weiyw17@gmail.com
#	2017.8.3

from rsf.proj import *

# define plot function 
def plotvel(File,title):
	Plot(File,'''
	grey title=%s color=j 
	scalebar=y
	''' % title)
# define other function

# get marmousi velocity model
Fetch('marmvel.hh', 'marm', server = 'local', top = '/Users/weiyw/workspace/fwi/swfwi/data')

# subsampling velocity 
Flow('vel','marmvel.hh',
'''
dd form=native |
window j1=5 j2=5 |
put label1=Depth unit1=m label2=Distance unit2=m
 ''')

# x-x ->> x-t
Flow('tau','vel',
'''
/Users/weiyw/workspace/fwi/swfwi/job/05/src/getTau
 ''')

# get max time
#nt = getsomeAttr("tau.rsf",'max') 

# regulation velocity & tau
Flow('pseuvel',"vel tau",
'''
pseudodepth tau=${SOURCES[1]} inv=n linear=y
n=20  o=0.0  d=0.01
 ''' )

End()
