# vim: fdm=marker fdl=0
# weiyw17@gmail.com	
# 2017.08.02

from rsf.proj import *

def plotvel(File,title): #{{{
	Plot(File,'''
	grey title=%s color=j
	scalebar=y scalelabel=Velocity scaleunit=m/s
	''' % title)
#}}}
def plotspectra(File,title): #{{{
	Plot(File,'''
	grey title=%s color=j
	scalebar=y scalelabel=Amplitude scaleunit=1
	''' % title )
#}}}
# creat velocity #{{{
Flow('vel','',
'''
math output="10*sin(x1/637.0)" unit=m/s label=Velocity 
n1=400 d1=10 n2=400 d2=10 o1=0 o2=0 
label1=Depth unit1=m label2=Distance unit2=m 
 ''')
#}}}

# plot velocity #{{{
plotvel('vel',"Velocity")
#}}}

# spectra of velocity #{{{
Flow('spectra-vel','vel',
'''
spectra all=n opt=y
 ''')
#}}}

# plot spectra #{{{
plotspectra('spectra-vel',"spectra of velocity")
#}}}

